#!/bin/bash

echo "Selecione uma opção para executar:"
echo "1 - Instalar & Iniciar"
echo "2 - Iniciar"
echo "3 - Encerrar"

read opcao

if [ $opcao == "1" ]; then
	sudo docker run --name xampp8 -p 41061:22 -p 80:80 -d -v $HOME/projetos:/opt/lampp/htdocs -v xampp8:/var/log/mysql/ tomsik68/xampp:8
	docker start xampp8
elif [ $opcao == "2" ]; then
	docker start xampp8
elif [ $opcao == "3" ]; then
	docker stop xampp8 -t 0
fi